### ISSUE TITLE
PAL games over-stretched horizontally

### ISSUE THREAD

**Issue by MeisterLLD** [OpenEmu/Mednafen-Core#13]
Here is an example from my PAL FF7.
http://imgur.com/a/vvaaK

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/Mednafen-Core/commit/08a6b696db7c4268414e75ba6fb8aedd6925dd91

**Comment by MeisterLLD** [comment]
I don't know whether this has been integrated in OpenEmu 2.0.5 but it's not fixed there
